version: 0.1 b{build}
image: Visual Studio 2015
configuration: Release
clone_depth: 1
clone_folder: c:\projects\tec
init:
- cmd: >-
    git config --global core.autocrlf input

    dir c:\

    cd C:\

    git clone https://github.com/adam4813/vcpkg

    cd vcpkg

    dir

    powershell -exec bypass scripts\bootstrap.ps1

    .\vcpkg integrate install

    .\vcpkg install asio bullet3 glew glfw3 glm lua openal-soft protobuf zlib

    cd c:\projects\tec
install:
- cmd: >-
    git submodule update --init
    
    cd c:\projects\tec

    mkdir build

    cd build

    cmake -G "Visual Studio 14 2015" -DBUILD_TESTS_TEC=True -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
build:
  project: c:\projects\tec\build\trillek.sln
  verbosity: minimal
  