version: 0.1 b{build}

clone_depth: 1

clone_folder: c:\projects\tec

init:
- git config --global core.autocrlf input

environment:
  LUA_DIR: c:\projects\tec\lib\
  
install:
- cd c:\projects\tec
- git submodule update --init

- appveyor DownloadFile "https://www.dropbox.com/s/m7vzruxrq8f79zo/tec_win32_libs.zip?dl=1&pv=1" -FileName tec_win32_libs.zip
- 7z x -y tec_win32_libs.zip -o"c:\projects\tec"

- mkdir build
- cd build
- cmake -G "Visual Studio 14 2015" -DBUILD_TESTS_TEC=True ..
  
build:
  project: c:\projects\tec\build\trillek.sln
  verbosity: minimal

test_script:
- .\build\bin\Debug\UNIT_TEST.exe
  